namespace: cf-trimana-dashboard
stacker_bucket_region: us-west-2
sys_path: ./

stacks:
  - name: bucket
    class_path: bucket.Trimana
    variables:
      env-dict:
        BucketName: trimana-dashboard-bucket

  - name: lambdas
    class_path: lambda.Trimana
    variables:
        env-dict:
          BucketName: trimana-dashboard-bucket
          LambdaName: trimana-dashboard-api

  - name: api
    class_path: api.Trimana
    variables:
        env-dict:
          ApiName: trimana-dashboard-api-gateway